import AuthProvider from './AuthProvider';
import './globals.css';
import { Inter } from 'next/font/google';

import { twMerge } from 'tailwind-merge';
import { ThemeProvider } from '@/providers/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          inter.className,
          'h-screen w-full dark flex flex-col '
        )}
      >
        {children}
      </body>
    </html>
  );
}
